apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoDataIndex
metadata:
  name: kogito-data-index
spec:
  # environment variables to set in the runtime container. Example: JAVA_OPTIONS: "-Dquarkus.log.level=DEBUG"
  #env:
    # - name: JAVA_OPTIONS
    #    value: "-Dquarkus.log.level=DEBUG"
  # number of pods to be deployed
  replicas: 1
  # image to use for this deploy
  image:
    tag: "0.7.0"
  # the http port that the dataindex image will listen internally
  #httpPort: 9090
  # Limits and requests for the Data Index pod
  #memoryLimit: ""
  #memoryRequest: ""
  #cpuLimit: ""
  #cpuRequest: ""
  # details about the kafka connection
  kafka:
    # will set this instance to auto provision an infra structure in the namespace
    useKogitoInfra: true
  # details about the connected infinispan
  infinispan:
    # will set this instance to auto provision an infra structure in the namespace and attach Infinispan credentials to it
    useKogitoInfra: true

