apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoApp
metadata:
  name: example-quarkus
spec:
  build:
    env:
      # this value is just an example, set yours (optional)
      - name: MAVEN_MIRROR_URL
        value: "http://nexus3.kogito-tools.svc.cluster.local:8081/repository/maven-public/"
    gitSource:
      contextDir: jbpm-quarkus-example
      uri: 'https://github.com/kiegroup/kogito-examples'
      reference: 0.6.1
    imageRuntime:
      imageStreamTag: 0.6.1
    imageS2I:
      imageStreamTag: 0.6.1
