apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoApp
metadata:
  name: example-springboot
spec:
  name: jbpm
  runtime: springboot
  env:
    - name: DEBUG
      value: "true"
  build:
    gitSource:
      uri: https://github.com/kiegroup/kogito-examples
      contextDir: jbpm-springboot-example
      reference: master
    incremental: true
    env:
      - name: CI
        value: "true"
