apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoDataIndex
metadata:
  name: kogito-data-index
spec:
  # environment variables to set in the runtime container. Example: JAVAOPTS: "-Dquarkus.log.level=DEBUG"
  # env: {}
  # number of pods to be deployed
  replicas: 1
  # image to use for this deploy
  image: "quay.io/kiegroup/kogito-data-index:latest"
  # Limits and requests for the Data Index pod
  memoryLimit: ""
  memoryRequest: ""
  cpuLimit: ""
  cpuRequest: ""
  # details about the kafka connection
  kafka:
    # the Kafka service instance to be used. Example: kogito-kafka
    instance: kogito-kafka
  # details about the connected infinispan
  infinispan:
    # let's leave this burden to KogitoInfra CR to deploy a new Infinispan instance for us
    useKogitoInfra: false
    # name of the auth realm. "default" is the realm name for 
    #authRealm: ""
    # default to PLAIN
    #saslMechanism: ""
    # the service name and port of the infinispan cluster. Example: my-infinispan:11222
    #uri: kogito-infinispan:11222
    # will automatically set to true if the credentials are set
    #useAuth: false
    # auth credentials
    #credentials:
      # the secret used to store the Infinispan credentials
      #secretName: ""
      # username key defined in the secret to read from
      #usernameKey: ""
      # password key defined in the secret
      #passwordKey: ""