apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: kogitocloud-operator.0.1.0
  namespace: placeholder
  annotations:
    categories: "Integration & Delivery"
    certified: "false"
    description: kogito Cloud Operator for deployment and management of quarkus services.
    repository: https://github.com/kiegroup/kogito-cloud-operator
    containerImage: quay.io/kiegroup/kogito-cloud-operator:0.1
    createdAt: 2019-04-30T12:48:22Z
    support: Red Hat, Inc.
    tectonic-visibility: ocs
    alm-examples: >-
      [{"apiVersion":"app.kiegroup.org/v1alpha1","kind":"KogitoApp","metadata":{"name":"example-quarkus"},"spec":{"build":{"gitSource":{"uri":"https://github.com/kiegroup/kogito-examples","contextDir":"jbpm-quarkus-example"}}}}]
  labels:
    operator-kogitocloud: "true"
spec:
  displayName: kogito Cloud
  description: kogito Cloud Operator for deployment and management of quarkus services.
  keywords:
    - cloud
    - kogito
    - quarkus
    - springboot
    - operator
  version: 0.1.0
  maturity: alpha
  maintainers:
    - name: Red Hat, Inc.
      email: bsig-cloud@redhat.com
  provider:
    name: Red Hat, Inc.
  links:
    - name: Product Page
      url: https://quarkus.io/
  icon:
    - base64data: PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMDAgMTAwIj48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2Q3MWUwMH0uY2xzLTJ7ZmlsbDojYzIxYTAwfS5jbHMtM3tmaWxsOiNmZmZ9LmNscy00e2ZpbGw6I2VhZWFlYX0uY2xzLTV7ZmlsbDojYjdiN2I3fS5jbHMtNntmaWxsOiNjZGNkY2R9PC9zdHlsZT48L2RlZnM+PHRpdGxlPkxvZ288L3RpdGxlPjxnIGlkPSJMYXllcl8xIiBkYXRhLW5hbWU9IkxheWVyIDEiPjxjaXJjbGUgY2xhc3M9ImNscy0xIiBjeD0iNTAiIGN5PSI1MCIgcj0iNTAiIHRyYW5zZm9ybT0icm90YXRlKC00NSA1MCA1MCkiLz48cGF0aCBjbGFzcz0iY2xzLTIiIGQ9Ik04NS4zNiAxNC42NGE1MCA1MCAwIDAgMS03MC43MiA3MC43MnoiLz48cGF0aCBjbGFzcz0iY2xzLTMiIGQ9Ik02NS43NiAzNC4yOEwxNS42IDQzLjE1djEuMTNhLjM0LjM0IDAgMCAwIC4zLjM0YzEuNDcuMTcgNy45MyAyLjExIDggMjMuNDlhLjQ2LjQ2IDAgMCAwIC4zNS40NGwyLjU5LjU3cy0xLjIxLTI1LjU0IDguNzctMjcuMDYgMTEuMiAyNy4yNyAxMS4zMyAzMS4xYS41NC41NCAwIDAgMCAuNDMuNTFsMy41MS43OHMuMDYtMzQuNTQgMTQuOTItMzYuODJ2LTMuMzV6Ii8+PHBhdGggY2xhc3M9ImNscy00IiBkPSJNNjUuMzUgMjcuNTZMMTYuMTggMzguNDJhLjc1Ljc1IDAgMCAwLS41OS43M3Y0bDUwLjE3LTguODd2LTYuNzZhMS42OCAxLjY4IDAgMCAwLS40MS4wNHoiLz48cGF0aCBjbGFzcz0iY2xzLTUiIGQ9Ik0zNS42MSA0Mi4wNWMtNC42MS43LTYuODMgNi41NC03Ljg5IDEyLjYxbDEzLjY1LTEuMzNjMC0uMTcuMDktLjM0LjEzLS41MXMuMTQtLjUzLjIxLS44bC4yLS42OHEuMTItLjQuMjUtLjhsLjItLjYyYy4xMi0uMzYuMjUtLjcxLjM5LTEuMDZsLjEyLS4zMmMtMS42NC00LjE3LTMuOTgtNi45OS03LjI2LTYuNDl6TTgyLjIzIDMxLjE5bC0xNi0zLjYyYTEuOSAxLjkgMCAwIDAtLjQyIDB2Ni43NmwxNy4wNiAyLjgzdi01LjIzYS43Ni43NiAwIDAgMC0uNjQtLjc0ek01My40MyA1My42MmwxOC40MS0xLjEzYzIuMS02LjA1IDUuNTEtMTEuNzUgMTEtMTIuOGwtMTctMi4wOGMtNi42OCAxLjEyLTEwLjM2IDguMjktMTIuNDEgMTYuMDF6Ii8+PHBhdGggY2xhc3M9ImNscy02IiBkPSJNNDEuNzEgNTJsLjEzLS40NS0uMTMuNDZ6TTQxLjkxIDUxLjM0bC0uMDYuMjIuMDctLjIzek0yNy43MiA1NC42NmE2OC4yNiA2OC4yNiAwIDAgMC0uOTMgMTJ2Mi40MkwzOSA2Ni4xYTEuMDYgMS4wNiAwIDAgMCAuODEtMSA1OC43MiA1OC43MiAwIDAgMSAxLjY5LTEyLjI2YzAgLjE2LS4wOS4zMy0uMTMuNDl6TTY1Ljc4IDM0LjI4bC4wMSAzLjM0IDE3LjAzIDIuMDd2LTIuNThsLTE3LjA0LTIuODN6TTUwLjg3IDc0LjQ0TDY4IDY4LjY4YS45Mi45MiAwIDAgMCAuNjMtLjc5IDcyLjQ2IDcyLjQ2IDAgMCAxIDMuMTgtMTUuNGwtMTguMzggMS4xM2E5MC45MSA5MC45MSAwIDAgMC0yLjU2IDIwLjgyek01My40MyA1My42MnoiLz48L2c+PC9zdmc+
      mediatype: image/svg+xml
  labels:
    alm-owner-kogitocloud: kogitocloud-operator
    operated-by: kogitocloud-operator.0.1.0
  selector:
    matchLabels:
      alm-owner-kogitocloud: kogitocloud-operator
      operated-by: kogitocloud-operator.0.1.0
  installModes:
    - type: OwnNamespace
      supported: true
    - type: SingleNamespace
      supported: true
    - type: MultiNamespace
      supported: false
    - type: AllNamespaces
      supported: false
  customresourcedefinitions:
    owned:
      - version: v1alpha1
        kind: KogitoApp
        description: A project prescription running a kogito service.
        displayName: KogitoApp
        name: kogitoapps.app.kiegroup.org
        resources:
          - kind: DeploymentConfig
            version: apps.openshift.io/v1
          - kind: Service
            version: v1
          - kind: Route
            version: route.openshift.io/v1
        specDescriptors:
          - description: Runtime
            displayName: Runtime
            path: runtime
            x-descriptors:
              - "urn:alm:descriptor:com.tectonic.ui:label"
        statusDescriptors:
          - description: Deployments for the KogitoApp environment.
            displayName: Deployments
            path: deployments
            x-descriptors:
              - "urn:alm:descriptor:com.tectonic.ui:podStatuses"
          - description: The address for accessing kogito service, if it is deployed.
            displayName: Route
            path: route
            x-descriptors:
              - "urn:alm:descriptor:org.w3:link"
  install:
    strategy: deployment
    spec:
      permissions:
        - serviceAccountName: kogito-cloud-operator
          rules:
            - apiGroups:
                - ""
                - app.kiegroup.org
                - apps.openshift.io
                - image.openshift.io
                - build.openshift.io
                - route.openshift.io
              resources:
                - "*"
              verbs:
                - "*"
            - apiGroups:
                - ""
              resources:
                - namespaces
              verbs:
                - get
            - apiGroups:
                - apps
              resources:
                - deployments
              verbs:
                - "*"
            - apiGroups:
                - monitoring.coreos.com
              resources:
                - servicemonitors
              verbs:
                - get
                - create
            - apiGroups:
                - apps
              resourceNames:
                - kogito-cloud-operator
              resources:
                - deployments/finalizers
              verbs:
                - update
      deployments:
        - name: kogito-cloud-operator
          spec:
            replicas: 1
            strategy:
              type: Recreate
            selector:
              matchLabels:
                name: kogito-cloud-operator
            template:
              metadata:
                labels:
                  name: kogito-cloud-operator
              spec:
                serviceAccountName: kogito-cloud-operator
                containers:
                  - name: kogito-cloud-operator
                    image: quay.io/kiegroup/kogito-cloud-operator:0.1
                    command:
                      - kogito-cloud-operator
                    imagePullPolicy: Always
                    env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: OPERATOR_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.labels['name']
                      - name: DEBUG
                        value: "false"
