apiVersion: apps/v1
kind: Deployment
metadata:
  name: kogito-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: kogito-operator
  template:
    metadata:
      labels:
        name: kogito-operator
    spec:
      serviceAccountName: kogito-operator
      containers:
        - name: kogito-cloud-operator
          image: quay.io/kiegroup/kogito-cloud-operator:0.8.0
          command:
            - kogito-cloud-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['name']
            - name: DEBUG
              value: "false"
